wechat-miniprogram/glass-easel

glass-easel/src/component.ts, glass-easel/src/tmpl/proc_gen_wrapper.ts, glass-easel/tests/core/misc.test.ts
If a component method is defined and returned in `init` function, it cannot be found in the component even if `writeFieldsToNode` option is enabled, and the `Component.getMethod` does not returns it. This PR fix this problem.
=> fix(core): cannot get component method defined from init

glass-easel/tests/types/chaining.test.ts, glass-easel/tests/types/createElement.test.ts, glass-easel/tests/types/definition.test.ts, package.json, pnpm-lock.yaml
Hi, I am maintaining of the `'tsd-lite'` package, which you are using for testing types (via [`'jest-runner-tsd'`](https://github.com/jest-community/jest-runner-tsd)).
Just noticed that you are importing the type tests assertions from `'tsd'`. It would be better to import from `'tsd-lite'`, because the assertions differ between the packages. (They are less buggy and more predictable in `'tsd-lite'`.)
This is the only change I made. (By the way, notice how many useless dependencies got removed.)
The upcoming release of `'tsd-lite'` will disallow importing from `'tsd'`. So this is a quick maintenance PR to help you upgrade smoother.
=> chore: import type testing assertions from `'tsd-lite'` package

glass-easel/src/element.ts
When a data update applies in `detached` lifetime, current implementation destroys children's backend elements before parent's element, which leads to backend call like `backendParent.spliceRemove(null, 1)`, and may cause unexpected results in backend.
This Pull Request destroys parent's backend element first, to prevent cases like this.
=> fix(core): destroy backend element earilier

glass-easel-template-compiler/src/js_bindings.rs
The array returned by the function "convert_str_arr" contains "holes".  Fix: Change "push" to "set".
=> fix: covert_str_arr return holes

glass-easel/src/backend/backend_protocol.ts, glass-easel/src/backend/composed_backend_protocol.ts, glass-easel/src/backend/domlike_backend_protocol.ts, glass-easel/src/element.ts, glass-easel/src/event.ts, glass-easel/src/index.ts, glass-easel/src/tmpl/proc_gen_wrapper.ts, glass-easel/tests/backend/domlike.test.ts
1. add `setDataset` for shadow backend
2. add `setListenerStats` replacing `setEventDefaultPrevented`
3. add `getContext` for elements with interactive context such as `<canvas />`
4. `FinalChanged` now representing the final state itself instead of state transitioning
=> Modify backend protocol for event-listener & context

glass-easel/src/class_list.ts, glass-easel/src/component.ts, glass-easel/src/native_node.ts, glass-easel/tests/legacy/component.test.js
```js
regElem({
is: 'comp',
options: {
styleScope: componentSpace.styleScopeManager.register('c'),
},
template: '<div id="c" class="c ^c1 ^^c2 ~c3" />',
})
var elem = createElem('comp')
expect(elem.$.c.$$.getAttribute('class')).toBe('c--c c--c1 c--c2 c--c3')
// expected 'c--c c--c1 c--c2 c--c3'
// got 'c--c c1 c--c2 c--c3'
```
Fixed the issue above, which got wrong style scope when the numbers of `^` exactly equals the depth in shadow tree.
Also refactored the constructor of `ClassList` for decoupling.
=> Fix caret class on root

glass-easel-template-compiler/src/tree.rs, glass-easel/src/tmpl/index.ts, glass-easel/src/tmpl/proc_gen_wrapper.ts, glass-easel/tests/base/env.ts, glass-easel/tests/core/misc.test.ts
1. Add `fallbackListenerOnNativeNode`  option to fallback `bindxxx` legacy event binding syntax on native nodes.
2. Remove `disallowNativeNode` option (use `setGlobalUsingComponent` api).
3. Change `ProcGenWrapper#r` to an arrow function for `this` expression compatibility.
4. Remove `R.r` generation in template compiler. **WARNING: This is a forward compatibility hazard**
=> fallback event listener on NativeNode

glass-easel/src/component.ts, glass-easel/src/component_space.ts, glass-easel/src/element.ts, glass-easel/src/native_node.ts, glass-easel/src/shadow_root.ts, glass-easel/src/tmpl/proc_gen_wrapper.ts
1. remove `placeholding` judgement from wrapper, since logics in `createComponent` is quite the same as `checkComponentPlaceholder`
2. always call `createComponent` (but not `createComponentOrNativeNode`) from wrapper `createCommonElement` as a result of _1_
3. rename `placeholderHandler` in `Element` to `placeholderHandlerRemover`, to improve readability
4. add `allowUnusedNativeNode` option to `ComponentSpace`, to allow unused tag name created as a `NativeNode`
=> Always call `createComponent` from wrapper `createCommonElement`

glass-easel-template-compiler/src/group.rs, glass-easel-template-compiler/src/tree.rs
Sometimes the imported names are not ready when codegen for a single tree. This change allows it.
=> feat: allow lazily checking of the imported names

glass-easel-template-compiler/src/tree.rs
Shorten generated code introduced in #110 a little bit by changing
```typescript
if (!S) {
S = {};
Object.assign(S, G['imports']._, H);
}
```
to
```typescript
if (!S) S = Object.assign({}, G['imports']._, H);
```
=> feat(template-compiler): shorten generated code

glass-easel/src/class_list.ts, glass-easel/src/component.ts, glass-easel/src/native_node.ts
made `classList` referencing `element` instead of  `backendElement` to avoid this
=> fix(core): classList may use backendElement after it is released

glass-easel-template-compiler/src/group.rs, glass-easel-template-compiler/src/proc_gen.rs, glass-easel-template-compiler/src/tree.rs
Hoist proc gen functions to increase updating performance.
proc-gen before this pr:
```js
return (() => {
var G = {};
var R = {};
var X = function (a) {
return a == null ? Object.create(null) : a;
};
var Y = function (a) {
return a == null ? "" : String(a);
};
var Z = function (a, b) {
if (a === true) return true;
if (a) return a[b];
};
var P = function (a) {
return typeof a === "function" ? a : () => {};
};
G[""] = (() => {
var H = {};
var S;
var I = (P) => {
if (!S) S = Object.assign({}, H);
return S[P];
};
H[""] = (R, C, D, U) => {
var L = R.c;
var M = R.m;
var O = R.r;
var A = {};
var K = U === true;
return {
C: (C, T, E, B, F) => {
F(
D.list,
null,
U ? U.list : undefined,
[0, "list"],
(C, a, b, c, d, e, T, E) => {
E(
"div",
{},
(N, C) => {},
(C, T, E) => {
E(
"x-c",
{},
(N, C) => { …
```
=> Hoist proc gen functions

glass-easel-template-compiler/src/proc_gen.rs, glass-easel-template-compiler/src/tree.rs, glass-easel/tests/tmpl/structure.test.ts
Template compiler will got wrong output when using wxs scripts
```html
// a.wxml
<wxs module="a">module.exports={ foo: 'foo' }</wxs>
<template name="test">
<div>{{a.foo}}</div>
</template>
<template is="test" />
```
=> Fix wxs scripts with template

glass-easel-template-compiler/src/proc_gen/mod.rs, glass-easel-template-compiler/src/proc_gen/tag.rs, glass-easel/src/tmpl/proc_gen_wrapper.ts, glass-easel/src/tmpl/proc_gen_wrapper_dom.ts, glass-easel/tests/core/placeholder.test.ts
Fix placeholder's dataset inside wx:for by creating an extra js scope for wx:for (and slot props).
Giving an example template `<child wx:for="{{arr}}" prop="{{item}}" data-index="{{index}}">{{index}}</child>`  Proc-gen generated code will be changed as the following:
```diff
- var i = (C, T) => {
-   C || K || g ? T(Y(e)) : T();
- },
c = (C, d, e, f, g, h, T, E) => {
+   var i = (C, T) => {
+     C || K || g ? T(Y(e)) : T();
+   };
E(
"child",
{},
(N, C) => {
if (C || K || f) O(N, "prop", d);
if (C || K || g) R.d(N, "index", e);
},
i
);
},
a = (C, T, E, B, F) => {
F(D.arr, null, U ? U.arr : undefined, [0, "arr"], c);
};
```
=> Fix placeholder's dataset inside wx:for

glass-easel-miniprogram-adapter/src/behavior.ts, glass-easel-miniprogram-adapter/src/builder/base_behavior_builder.ts, glass-easel-miniprogram-adapter/src/builder/behavior_builder.ts, glass-easel-miniprogram-adapter/src/builder/component_builder.ts, glass-easel-miniprogram-adapter/src/component.ts, glass-easel-miniprogram-adapter/tests/space.test.ts, glass-easel/src/behavior.ts, glass-easel/src/component.ts, glass-easel/src/component_params.ts, glass-easel/src/component_space.ts, glass-easel/tests/core/behavior.test.ts
Add extraThisFieldsType to enhance type completeness of ComponentInstance, which makes custom properties and methods type safe on "this"
- chaining api only
- on legacy framework need a polyfill which could convert chaining api to mini-program-like api
=> feat: support extraThisFieldsType(#70)

glass-easel/src/element.ts, glass-easel/src/element_iterator.ts, glass-easel/tests/core/element_iterator.test.ts
Added `[Symbol.iterator]` for ElementIterator, which can support subtree-level breaking:
- Passing false into the iterator (aka `iterator.next(false)`) will skip the following subtree
- Breaking the iterator will skip the whole iteration
Examples:
```js
for (let node of glassEasel.ElementIterator.create(
g,
glassEasel.ElementIteratorType.ShadowDescendantsRootFirst,
Object,
)) {
// iterate here
}
```
=> Allow breaking subtree for element-iterator

glass-easel-template-compiler/src/js_bindings.rs, glass-easel-template-compiler/src/parse/mod.rs
JavaScript version for #145
Also change `TemplateParseError` to camelCase to better fit in JavaScript
=> Allow template-compiler js-bindings to obtain template parse error level

glass-easel-miniprogram-adapter/src/component.ts
Callbacks for data update methods should be called with `ComponentCaller` as `this`, and should be wrapped with a `safeCallback`
=> Data update method callbacks wrapper

glass-easel-template-compiler/src/parse/expr.rs, glass-easel-template-compiler/src/proc_gen/expr.rs, glass-easel-template-compiler/src/stringify/expr.rs, glass-easel/tests/tmpl/expression.test.ts
=> Fix template ops

glass-easel/src/behavior.ts, glass-easel/src/data_proxy.ts, glass-easel/tests/legacy/component.test.js
Changes:
1. `property.value` will only be used for determining the initial value of a property
2. ensure that initial data and property values will never be `undefined` when calling `property.default` throws an error
Breaking change: when determining initial value of a property, if `property.default` throws an error, `property.value` will be used in current implementation; now a fallback value will be used, which means `property.value` will be completely ignored when `property.default` is a function.
=> Refactor property value and default function resolution

glass-easel-miniprogram-adapter/src/builder/type_utils.ts, glass-easel-miniprogram-template/webpack.config.js, glass-easel-miniprogram-webpack-plugin/README.md, glass-easel-miniprogram-webpack-plugin/index.ts, glass-easel-template-compiler/src/cbinding.rs, glass-easel-template-compiler/src/group.rs, glass-easel-template-compiler/src/js_bindings.rs, glass-easel-template-compiler/src/proc_gen/tag.rs, glass-easel/src/backend/current_window_backend_context.ts, glass-easel/src/backend/shared.ts, glass-easel/src/backend/suggested_backend_protocol.ts, glass-easel/src/behavior.ts, glass-easel/src/class_list.ts, glass-easel/src/component.ts, glass-easel/src/data_proxy.ts, glass-easel/src/dev_tools.ts, glass-easel/src/element.ts, glass-easel/src/index.ts, glass-easel/src/mutation_observer.ts, glass-easel/src/node.ts, glass-easel/src/shadow_root.ts, glass-easel/src/text_node.ts, glass-easel/src/tmpl/index.ts, glass-easel/src/tmpl/proc_gen_wrapper.ts, glass-easel/src/tmpl/proc_gen_wrapper_dom.ts, glass-easel/tests/base/env.ts, glass-easel/tests/core/element_iterator.test.ts, glass-easel/tests/core/mutation_observer.test.ts, glass-easel/tests/legacy/mutation_observer.test.js, glass-easel/tests/tmpl/dev_mode.test.ts
`MutationObserver` changes:
* Events with `characterData` type will now target at the TextNode itself (not its parent);
* More attributes can be returned with `properties` type.
=> feat: new API for inspector

glass-easel-miniprogram-adapter/src/backend.ts, glass-easel-miniprogram-adapter/src/space.ts, glass-easel-miniprogram-adapter/tests/env.test.ts, glass-easel-miniprogram-adapter/tests/selector.test.ts, glass-easel-miniprogram-adapter/tests/space.test.ts, glass-easel-miniprogram-adapter/tests/trait_behavior.test.ts, glass-easel-miniprogram-webpack-plugin/index.ts, glass-easel-miniprogram-webpack-plugin/wxss_loader.js, glass-easel-stylesheet-compiler/src/js_bindings.rs, glass-easel-stylesheet-compiler/src/lib.rs, glass-easel-stylesheet-compiler/src/main.rs, glass-easel/src/component.ts, glass-easel/src/component_space.ts, glass-easel/tests/base/composed_backend.ts, glass-easel/tests/base/env.ts, glass-easel/tests/base/shadow_backend.ts, glass-easel/tests/core/behavior.test.ts, glass-easel/tests/core/component_space.test.ts, glass-easel/tests/core/data_update.test.ts, glass-easel/tests/core/placeholder.test.ts, glass-easel/tests/core/slot.test.ts, glass-easel/tests/core/trait_behaviors.test.ts, glass-easel/tests/tmpl/binding_map.test.ts, glass-easel/tests/tmpl/lvalue.test.ts, glass-easel/tests/tmpl/native_rendering.test.ts, glass-easel/tests/tmpl/structure.test.ts
Changed to use style scope as the `:host` compilation result, i.e. `:host` converted to `[wx-host="STYLE_SCOPE"]` where the `STYLE_SCOPE` is the style scope name of the component.
This makes the implementation of composed backends easier.
However, shared style scope will result in shared `:host` styles. To avoid this problem, `ComponentSpace#setSharedStyleScope` is introduced. If the `options.styleScope` of the component matches this "shared" style scope, the `wx-host` attribute will not be applied, in other words, the `:host` of the component will not take effect.
=> feat: new host style support based on style scope

glass-easel/src/tmpl/proc_gen_wrapper.ts, glass-easel/tests/tmpl/event.test.ts
1. let property change listener takes effect on all "property-like" attributes, like `class`, `style`, `id`, `slot` or non-property attributes on NativeNode
2. call property change listener with `this` set to `null`, and related component set to owner host
3. initialize a property change listener with `undefined` as first old value
4. change methods for procGen in `ProcGenWrapper` to arrow function, to avoid `this` missing in template calls
=> Expand effective range of changePropListener

glass-easel/src/element.ts
Introduced by #49 
Placeholder handlers for NativeNode are not properly removed when adding support for NativeNode as placeholder.
=> fix(core): remove placeholderHandler for native node

glass-easel/src/component.ts, glass-easel/src/component_space.ts, glass-easel/src/element.ts
1. `placeholderHandlerRemover` do not initialized properly for `Component`
2. `placeholderHandlerRemover` may be missed if a component detached before it is attached
3. `ComponentWaitingList`'s `remove` may be called during its own `call`
=> fix(core): placeholderHandler do not trigger properly

glass-easel/src/component_space.ts
Properly handles when `placeholderReplacer` to be remove is not in the queue
=> fix(core): remove placeholderReplacer properly

glass-easel/src/tmpl/range_list_diff.ts
This fixes error caused by passing `NaN` to `wx:for`, since `arrayLength` should be an integer between 0 and 2<sup>32</sup> - 1 (inclusive)
=> fix(core): ensure numeric for-value to be valid array length

glass-easel-miniprogram-adapter/src/behavior.ts, glass-easel-miniprogram-adapter/src/builder/base_behavior_builder.ts, glass-easel-miniprogram-adapter/src/builder/behavior_builder.ts, glass-easel-miniprogram-adapter/src/builder/component_builder.ts, glass-easel-miniprogram-adapter/src/builder/index.ts, glass-easel-miniprogram-adapter/src/builder/type_utils.ts, glass-easel-miniprogram-adapter/src/component.ts, glass-easel-miniprogram-adapter/src/space.ts, glass-easel-miniprogram-adapter/tests/env.test.ts, glass-easel-miniprogram-adapter/tests/selector.test.ts, glass-easel-miniprogram-adapter/tests/space.test.ts
1. remove default generic value from builder types and component types, which have many generics, to prevent lossing or misplacing generics during passing;
1. explicitly specifies generic values for defaults of builder types and generals for component types;
1. generic for `extraThisFields` is missing from `ComponentType`, which made `extraThisFields` not working on instance comes from `selectComponent*`
1. `Component` from `space.componentEnv` with a definition should returns a `ComponentType` rather than `void`
1. `Behavior` from `space.componentEnv` with a definition should have a corresponding `Component` as its `ThisType` for accessing `this` in methods or lifetimes (similars to `BehaviorBuilder.definition` in core)
1. components and behaviors should be able to use `export` from …
=> Fix: several issues due to generic typing

glass-easel/src/tmpl/range_list_diff.ts, glass-easel/tests/core/data_update.test.ts
When wx:key is invalid and a unique key becomes shared key during updates, e.g. `[ { key: 'a' } ]` changed to `[ { key: 'a' }, { key: 'a' } ]` , it causes an extra removal+insertion. This PR fixes this behavior.
=> fix: avoid removal/insertion when removal one of last 2 shared-keys

glass-easel-template-compiler/src/escape.rs, glass-easel-template-compiler/src/parse/tag.rs, glass-easel-template-compiler/src/proc_gen/tag.rs, glass-easel-template-compiler/src/stringify/tag.rs, glass-easel/src/tmpl/proc_gen_wrapper.ts, glass-easel/tests/tmpl/structure.test.ts
RT
In legacy framework, `data-xxx` is also treated as component property names in dash form! This fix also includes compatibilities for this behavior.
=> Allow `data-*` in template attrs to be component properties and external classes
